src/Entity/Payment.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PaymentRepository")
 */
class Payment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="payments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=Galery::class, inversedBy="payments")
     */
    private $galery;

    /**
     * @ORM\Column(type="datetime")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $endDate;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pId;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getGalery(): ?Galery
    {
        return $this->galery;
    }

    public function setGalery(?Galery $galery): self
    {
        $this->galery = $galery;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getPId(): ?string
    {
        return $this->pId;
    }

    public function setPId(string $pId): self
    {
        $this->pId = $pId;

        return $this;
    }

    public function setPremiumDuration(?string $interval): self
    {
        $date = new \DateTime();

        if ($this->isPremium()) {
            $endDate = $this->getEndDate();
            $date->setTimestamp($endDate->getTimestamp());
        }

        $this->endDate = $interval == null ? $interval : $date->add(new \DateInterval($interval));

        return $this;
    }

    public function isPremium(): bool
    {
        $now = new \DateTime();
        $endDate = $this->getEndDate();

        return $endDate > $now;
    }

    public function getRemainingTime(): string
    {
        $diff = date_diff($this->getEndDate(), new DateTime())->format('%H h %I');

        return $diff;
    }

    public function get($property) {
        if (property_exists($this, $property)) {
            return $this->$property;
        }
        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function __toString()
    {
        return $this->getPId();
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\ProfileFormType;
use App\Form\UpdatePasswordFormType;
use App\Repository\CommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{
    /**
     * @Route("/connexion", name="security_login")
     */
    public function login(Request $request, AuthenticationUtils $authenticationUtils)
    {
        // If user is already connected.
        if ($this->getUser()) {
            return $this->redirectToRoute('security_user_profile');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    /**
     * @Route("/logout", name="security_logout")
     */
    public function logout(){}
    
    /**
     * @Route("/mon-compte/", name="security_user_profile")
     */
    public function userProfile(Request $request, EntityManagerInterface $manager, UserPasswordEncoderInterface $encoder)
    {
        // If user is not connected
        if (!$user = $this->getUser()) {
            return $this->redirectToRoute('home');
        }

        $formPassword = $this->createForm(UpdatePasswordFormType::class, $user, ['validation_groups' => ['User']]);
        $formProfile = $this->createForm(ProfileFormType::class, $user);

        $action = $request->get('action');
        if ('profile' === $action) {
            $formProfile->handleRequest($request);
        } elseif ('password' === $action) {
            $formPassword->handleRequest($request);
        }
        
        // Password update.
        if ($formPassword->isSubmitted() && $formPassword->isValid()) {
            $data = $formPassword->getData();
            $user->setPassword($encoder->encodePassword($user, $data->getPassword()));
            $user->setUpdatedAt(new \DateTime('now'));
            $manager->flush();

            $this->addFlash('success', 'Votre mot de passe a bien été mis à jour');

            return $this->redirectToRoute('security_user_profile');
        }

        // Email & avatar update.
        if ($formProfile->isSubmitted() && $formProfile->isValid()) {
            $user->setUpdatedAt(new \DateTime('now'));
            $manager->flush();

            $this->addFlash('success', 'Votre profil a bien été mis à jour');

            return $this->redirectToRoute('security_user_profile');
        }


        return $this->render('security/user_profile.html.twig', [
            'user'  => $user,
            'galeries' => $user->getLikedGaleries(),
            'form_profile' => $formProfile->createView(),
            'form_password' => $formPassword->createView(),
        ]);
    }

    /**
    * @Route("/profil/{username}", name="user.show")
    * @param User $user
    * @param CommentRepository $commentRepository
    * @return Response
    */
    public function show(User $user, CommentRepository $commentRepository) 
    {
        $comments = $commentRepository->findBy(['user' => $user->getId()], ['createdAt' => 'DESC'], 3);

        return $this->render('security/user_show.html.twig', [
            'user' => $user,
            'galeries' => $user->getLikedGaleries(),
            'comments' => $comments
        ]);
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% set title = 'Connexion' %}

{% block body %}
<div class="wrapper pattern-wrapper bg-image" data-image-src="{{ asset('assets/form_bg.jpg') }}" style="background-image: url({{ asset('assets/form_bg.jpg') }});">
    <div class="container inner">
        <div class="row">
            <div class="security-form col-lg-10 offset-lg-1 col-xl-6 offset-xl-3 bg-white">
            <span class="vertical_logo fill-light size-200">
                {{ include('icon/vertical_logo.html.twig') }}
            </span>
                {% for message in app.flashes('verify_email_error') %}
                    <div class="alert alert-danger mb-30">
                        {{ message }}
                    </div>
                {% endfor %}
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success mb-30">
                        {{ message }}
                    </div>
                {% endfor %}
                {% if error %}
                    <div class="alert alert-danger mb-30">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                {% endif %}
                <h1 class="section-title section-title-upper large section-title-underline text-center">Connexion</h1>
                <div class="space50"></div>
                <form action="{{ path('security_login') }}" method="post">
                    <div class="row">
                        <div class="col-10 offset-1">
                            <div class="form-group">
                                {# <label for="_username">Adresse email</label> #}
                                <input name="_username" placeholder="Nom d'utilisateur" required type="text" class="form-control" value="{{ last_username }}">
                            </div>
                        </div>
                        <div class="col-10 offset-1">
                            <div class="form-group">
                                {# <label for="_username">Mot de passe</label> #}
                                <input name="_password" placeholder="Mot de passe..." required type="password" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-10 offset-1 text-right mb-15">
                            <a href="{{ path('app_forgot_password_request') }}">mot de passe oublié ?</a>
                        </div>
                        <div class="col-10 col-md-5 offset-1">
                            <div class="form-group">
                                <div class="custom-control custom-checkbox">
                                    <input class="custom-control-input" type="checkbox" id="remember_me" name="_remember_me" checked/>
                                    <label class="custom-control-label" for="remember_me">Se souvenir moi</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-10 offset-1 col-md-5">
                            <div class="form-group">
                                <button type="submit" class="btn btn-xs btn-dark">Se connecter</button>
                            </div>
                        </div>
                        <div class="col-10 offset-1 text-center">
                                Vous n'avez pas de compte ? <a href="{{ path('security_registration') }}">Inscrivez-vous !</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/security/user_profile.html.twig
{% extends 'base.html.twig' %}
{% import 'component/macros.html.twig' as macros %}
{% form_theme form_profile with ['form/form_row.html.twig', 'form/form_errors.html.twig'] %}
{% form_theme form_password with ['form/form_row.html.twig', 'form/form_errors.html.twig'] %}

{% set title = 'Mon compte' %}

{% block body %}
<div class="wrapper light-wrapper">
    <div class="container">
        <div class="col-12">
            <div class="space50"></div>
            <h1 class="section-title section-title-upper section-title-underline text-center mb-50">Mon compte</h1>

            <div class="col-10 offset-1">
                {% for message in app.flashes('success') %}
                <div data-aos="fade" class="alert alert-success">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            
            {# {% if not user.isVerified %}
                <div class="col-10 offset-1">
                    <div data-aos="fade" class="alert alert-warning mt-20">
                        Vous devez vérifier votre e-mail pour activer votre compte, vérifiez votre boite mail. <a href="{{ path('send_verification_email', {user: user.id}) }}">Renvoyer-l'email de confirmaton</a>.
                    </div>
                </div>
            {% endif %} #}
                <h2 class="pt-30">Hello, <span class="color-blue-green text-center">{{ user.username }} !</span></h2>

                {{ form_start(form_profile, { 'action': path('security_user_profile'), 'attr': { 'id': 'profil_form', 'class': 'security_user_profile', 'novalidate': 'novalidate' } }) }}
                <div class="row pt-20 pb-40">
                    <div class="col-md-3">
                        <div class="form-group">
                            <div class="avatar-container">
                                <div class="user icon overlay">
                                    <div id="avatar" style="background-image: url({{ vich_uploader_asset(user, 'imageFile') }})"></div>
                                    <div id="edit-avatar" role="button" style="font-size:13px;">Modifier</div>
                                </div>
                                {# <div id="delete-avatar" role="button"></div> #}
                            </div>
                            {{ form_widget(form_profile.imageFile, {'label' : 'Avatar', 'class' : 'form-control'}) }}
                        </div>

                        <div class="form-group">
                            {{ form_row(form_profile.email, {'label' : 'Adresse email', 'attr': {'placeholder' : 'Adresse email', 'class' : 'form-control'}})
                            }}
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-xs btn-dark lead" name="action"
                                value="profile">Enregistrer</button>
                        </div>
                        {{ form_end(form_profile) }}
                    </div>

                    <div class="col-md-4 py-2">
                        {{ form_start(form_password)  }}
                        <h3 class="sub-heading3 text-uppercase pb-20">Changer de MDP</h3>

                        <div class="form-group">
                            {{ form_row(form_password.password.first, {'label' : 'Mot de passe', 'attr': {'placeholder' : 'Mot de passe', 'class' : 'form-control'}})
                            }}
                        </div>
                        <div class="form-group">
                            {{ form_row(form_password.password.second, {'label' : 'Confirmation du mot de passe', 'attr': {'placeholder' : 'Confimer le mot de passe', 'class' : 'form-control'}})
                            }}
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-xs btn-dark lead" name="action"
                                value="password">Enregistrer</button>
                        </div>
                        {{ form_end(form_password) }}
                    </div>

                    <div class="col-md-5">
                        <div class="py-2 px-4 ml-40">
                            <h3 class="sub-heading3 text-uppercase">Profil</h3>
                            <span class="custom-comments fill-black size-20">
                                {{ include('icon/comments.html.twig') }}
                                <span class="color-blue-green text-center">{{ user.comments|length }}</span> commentaire(s)
                            </span>
                        </div>

                        <div class="subscription mt-10 border py-2 px-4 ml-40">
                            <h3 class="sub-heading3 text-uppercase">Abonnement</h3>
                            <p>
                                <span class="lead2 color-dark">
                                    {% if user.isPremium() %}
                                            Abonné(e) jusqu'au {{ user.premium|localizeddate('medium', 'none') }} - <span class="color-blue-green">Corbies</span>
                                    {% else %}
                                        {% if user.premium is null %}
                                            Vous n'êtes pas abonné(e)
                                        {% else %}
                                            Abonnement expiré le {{ user.premium|localizeddate('medium', 'none') }}
                                        {% endif %}
                                    {% endif %}
                                </span>
                            </p>

                            {% if user.getRented() is not empty %}
                            <div class="widget">
                                <h3 class="sub-heading3 text-uppercase">Vos locations</h3>
                                <ul class="image-list">
                                    {% for rent in user.getRented() %}
                                        <li>
                                            <figure>
                                                <a href="{{ path('galery.show', {slug: rent.galery.slug}) }}">
                                                    {{ macros.image(
                                                        vich_uploader_asset(rent.galery, 'thumbnailFile'),
                                                        70,
                                                        70,
                                                        {'class': 'img-fluid', 'alt': 'Miniature de la galerie "' ~ rent.galery.title ~ '"'},
                                                        {'fit': 'crop'}
                                                    ) }}
                                                </a>
                                            </figure>
                                            <div class="post-content">
                                                <h6 class="post-title">
                                                    <a href="{{ path('galery.show', {slug: rent.galery.slug}) }}">{{ rent.galery.title }}</a> 
                                                </h6>
                                                <div class="meta">
                                                    <i class="fa fa-clock-o"></i>
                                                    <span class="far fa-clock">{{ rent.getRemainingTime() }}</span>
                                                    
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                                <!-- /.image-list --> 
                            </div>
                            <!-- /.widget --> 
                            {% endif %}
                        </div>
                    </div>
                </div>

                {% if galeries is not empty %}
                <div class="pt-20 pb-50" data-aos="fade-up">
                    <h3 class="pb-20 sub-heading3 text-uppercase">Galeries aimé</h3>
                    {{ include('galery/_preview.html.twig', { galeries: galeries, col: '4' }) }}
                </div>
                {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/security/user_show.html.twig
{% extends 'base.html.twig' %}
{% import 'component/macros.html.twig' as macros %}
{% set title = 'Profil de ' ~ user.username %}

{% block body %}
<div class="wrapper light-wrapper">
    <div class="container">
        <div class="col-12">
            <div class="space50"></div>
            <h1 class="section-title section-title-upper section-title-underline text-center mb-50">Profil de
                {{ user.username }}</h1>
            <div class="row pt-20 pb-20">
                <div class="col-md-6">
                    <div class="py-2">
                        <h3 class="sub-heading3 text-uppercase">Statistiques</h3>
                        <span class="text-dark">
                            <i class="fa fa-calendar"></i> Inscrit le
                            <span class="color-blue-green text-center">{{ user.createdAt|localizeddate('medium', 'none') }}</span>
                        </span> 
                        <br>
                        <span class="custom-comments fill-black size-20">
                            {{ include('icon/comments.html.twig') }}
                            <span class="color-blue-green text-center">{{ user.comments|length }}</span> commentaire(s)
                        </span>
                        <br>
                        <span class="fill-black size-20">
                            {{ include('icon/heart.html.twig') }}
                            <span class="color-blue-green text-center">{{ user.likedGaleries|length }}</span> galerie(s)
                            aimé(s)
                        </span>
                    </div>

                    <div class="subscription mt-10 border py-2 px-3">
                        <h3 class="sub-heading3 text-uppercase">Abonnement</h3>
                        <p>
                            <span class="lead2 color-dark">
                                {% if user.isPremium() %}
                                Abonné(e) jusqu'au {{ user.premium|localizeddate('medium', 'none') }} - <span
                                    class="color-blue-green">Corbies</span>
                                {% else %}
                                {% if user.premium is null %}
                                Vous n'êtes pas abonné(e)
                                {% else %}
                                Abonnement expiré le {{ user.premium|localizeddate('medium', 'none') }}
                                {% endif %}
                                {% endif %}
                            </span>
                        </p>

                        {% if user.getRented() is not empty %}
                        <div class="widget">
                            <h3 class="sub-heading3 text-uppercase">Vos locations</h3>
                            <ul class="image-list">
                                {% for rent in user.getRented() %}
                                <li>
                                    <figure>
                                        <a href="{{ path('galery.show', {slug: rent.galery.slug}) }}">
                                            {{ macros.image(
                                                vich_uploader_asset(rent.galery, 'thumbnailFile'),
                                                70,
                                                70,
                                                {'class': 'img-fluid', 'alt': 'Miniature de la galerie "' ~ rent.galery.title ~ '"'},
                                                {'fit': 'crop'}
                                            ) }}
                                        </a>
                                    </figure>
                                    <div class="post-content">
                                        <h6 class="post-title">
                                            <a
                                                href="{{ path('galery.show', {slug: rent.galery.slug}) }}">{{ rent.galery.title }}</a>
                                        </h6>
                                        <div class="meta">
                                            <i class="fa fa-clock-o"></i>
                                            <span class="far fa-clock">{{ rent.getRemainingTime() }}</span>

                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                            <!-- /.image-list -->
                        </div>
                        <!-- /.widget -->
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div id="comments">
                        <h3 class="sub-heading3 text-uppercase">Derniers commentaires</h3>
                        <ol id="singlecomments" class="commentlist">
                            {% for comment in comments %}
                            {% if not comment.isReply %}
                                {{ include('comment/_single_comment.html.twig', { user: comment.user, galery: { id: null} }) }}
                            {% endif %}
                            {% endfor %}
                        </ol>
                    </div>
                </div>
            </div>


            {% if galeries is not empty %}
            <div class="pt-20 pb-50" data-aos="fade-up">
                <h3 class="pb-20 sub-heading3 text-uppercase">Galeries aimé</h3>
                {{ include('galery/_preview.html.twig', { galeries: galeries, col: '4' }) }}
            </div>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}