src/Entity/Galery.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\GaleryRepository")
 * @Vich\Uploadable()
 */
class Galery
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $thumbnail;

    /**
     * @var File
     * @Vich\UploadableField(mapping="galery_thumbnails", fileNameProperty="thumbnail")
     */
    private $thumbnailFile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", mappedBy="galeries", cascade={"persist"})
     */
    private $categories;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Model", mappedBy="galeries")
     */
    private $models;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="galery", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updatedAt;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isFree;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="likedGaleries")
     */
    private $userLikes;

    /**
     * @ORM\OneToMany(targetEntity=Attachment::class, mappedBy="galery", orphanRemoval=true, cascade={"persist"})
     */
    private $attachments;

    /**
     * Admin field
     */
    private $attachmentFiles;

    /**
     * @ORM\Column(type="integer")
     */
    private $cupOfCoffee;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPublished;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $banner;

    /**
     * @var File
     * @Vich\UploadableField(mapping="galery_banner", fileNameProperty="banner")
     */
    private $bannerFile;

    /**
     * @ORM\OneToMany(targetEntity=Payment::class, mappedBy="galery")
     */
    private $payments;

    public function __construct()
    {
        $this->thumbnail = '../../../assets/default/thumbnail.png';
        $this->createdAt = new \DateTime('now');
        $this->categories = new ArrayCollection();
        $this->models = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->userLikes = new ArrayCollection();
        $this->attachments = new ArrayCollection();
        $this->cupOfCoffee = 0;
        $this->payments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function setThumbnailFile(File $thumbnail = null)
    {
        $this->thumbnailFile = $thumbnail;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($thumbnail) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getThumbnailFile()
    {
        return $this->thumbnailFile;
    }

    public function getThumbnail(): ?string
    {
        return $this->thumbnail;
    }

    public function setThumbnail($thumbnail): self
    {
        $this->thumbnail = $thumbnail;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->addGalery($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
            $category->removeGalery($this);
        }

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function __toString()
    {
        return $this->getTitle();
    }

    /**
     * @return Collection|Model[]
     */
    public function getModels(): Collection
    {
        return $this->models;
    }

    public function addModel(Model $model): self
    {
        if (!$this->models->contains($model)) {
            $this->models[] = $model;
            $model->addGalery($this);
        }

        return $this;
    }

    public function removeModel(Model $model): self
    {
        if ($this->models->contains($model)) {
            $this->models->removeElement($model);
            $model->removeGalery($this);
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setGalery($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getGalery() === $this) {
                $comment->setGalery(null);
            }
        }

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getAttachmentFiles()
    {
        return $this->attachmentFiles;
    }

    /**
     * @return String
     */
    public function getCategoriesName(): String
    {
        setlocale(LC_CTYPE,'fr_FR');
        $result = '';

        foreach ($this->categories as $categorie){
            $result .= $categorie->getTranslitName() . ' ';
        }

        return $result;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIsFree(): ?bool
    {
        return $this->isFree;
    }

    public function setIsFree(bool $isFree): self
    {
        $this->isFree = $isFree;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUserLikes(): Collection
    {
        return $this->userLikes;
    }

    public function addUserLike(User $userLike): self
    {
        if (!$this->userLikes->contains($userLike)) {
            $this->userLikes[] = $userLike;
        }

        return $this;
    }

    public function removeUserLike(User $userLike): self
    {
        if ($this->userLikes->contains($userLike)) {
            $this->userLikes->removeElement($userLike);
        }

        return $this;
    }

    /**
     * @return Collection|Attachment[]
     */
    public function getAttachments(): Collection
    {
        return $this->attachments;
    }

    public function addAttachment(Attachment $attachment): self
    {
        if (!$this->attachments->contains($attachment)) {
            $this->attachments[] = $attachment;
            $attachment->setGalery($this);
        }

        return $this;
    }

    public function removeAttachment(Attachment $attachment): self
    {
        if ($this->attachments->contains($attachment)) {
            $this->attachments->removeElement($attachment);
            // set the owning side to null (unless already changed)
            if ($attachment->getGalery() === $this) {
                $attachment->setGalery(null);
            }
        }

        return $this;
    }

    public function getCupOfCoffee(): ?int
    {
        return $this->cupOfCoffee;
    }

    public function setCupOfCoffee(int $cupOfCoffee): self
    {
        $this->cupOfCoffee = $cupOfCoffee;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getBanner(): ?string
    {
        return $this->banner;
    }

    public function setBanner(?string $banner): self
    {
        $this->banner = $banner;

        return $this;
    }

    public function setBannerFile(File $banner = null)
    {
        $this->bannerFile = $banner;

        // VERY IMPORTANT:

src/Controller/GaleryController.php
<?php

namespace App\Controller;

use App\Entity\Galery;
use App\Repository\GaleryRepository;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class GaleryController extends AbstractController
{
    /**
     * @Route("/galeries", name="galeries")
     * @param GaleryRepository $GaleryRepository
     * @param CategoryRepository $CategoryRepository
     */
    public function index(GaleryRepository $GaleryRepository, CategoryRepository $CategoryRepository)
    {
        $galeries = $GaleryRepository->findBy(['isPublished' => true]);
        $categories = $CategoryRepository->findAll();

        return $this->render('galery/index.html.twig', [
            'galeries' => $galeries,
            'categories' => $categories,
        ]);
    }

    /**
    * @Route("/galerie/{slug}", name="galery.show")
    * @param Galery $galery
    * @return Response
    */
    public function show(Galery $galery, GaleryRepository $repository) 
    {
        if (isset($_GET['transaction']) && $user = $this->getUser()) {
            if ($_GET['transaction'] == 'rent') {
                $message = 'Transaction terminée ! Vous louez cette galerie jusqu\'au ' . $user->getRentingTime($galery);
            } else {
                $message = 'Transaction terminée ! Vous êtes abonné jusqu\'au ' . $user->getPremium()->format('d/m/Y');
            }

            $this->addFlash('success', $message);
            return $this->redirectToRoute('galery.show', ['slug' => $galery->getSlug()]);
        }

        $categories = $galery->getCategories();

        $related_galeries = $repository->findByCategory($categories);
        return $this->render('galery/show.html.twig', ['galery' => $galery, 'related_galeries' => $related_galeries]);
    }

    /**
     * @param GaleryRepository $GaleryRepository
     */
    public function popularGaleries(GaleryRepository $repository) {
        $galeries = $repository->findPopular();

        return $this->render('galery/_popular.html.twig', [
            'galeries' => $galeries
        ]);
    }

    /**
    * @Route("/like/{galery}/", name="galery.like", options={"expose"=true})
    * @param Galery $galery
    * @return Response
    */
    public function like(Galery $galery, EntityManagerInterface $manager, Request $request) {
        // If user is not connected, abord.
        if (!$this->getUser()) {
            return $this->redirectToRoute('home');
        }

        if ($request->getMethod() === 'POST' && $request->isXmlHttpRequest()) {
            
            // If galery doesn't exsit, return empty response.
            if (!$galery) {
                return new JsonResponse();
            }
            
            $csrfToken = $request->request->get('csrfToken');
            
            // CHeck that the crsfToken is valid.
            if ($this->isCsrfTokenValid('galery' . $galery->getId(), $csrfToken)) {
                $user = $this->getUser();

                if ($user->isLiking($galery)) {
                    $user->removeLikedGalery($galery);
                } else {
                    $user->addLikedGalery($galery);
                }
        
                $manager->flush(); 
            }
        }
        return new JsonResponse(count($galery->getUserLikes()));
    }
}

templates/galery/_popular.html.twig
{% import 'component/macros.html.twig' as macros %}

<div class="widget">
    <h3 class="widget-title text-center text-md-left">Galeries Populaires</h3>
    <ul class="image-list">
        {% for galery in galeries %}
            <li>
                <figure>
                    <a href="{{ path('galery.show', {slug: galery.slug}) }}">
                        {{ macros.image(
                            vich_uploader_asset(galery, 'thumbnailFile'),
                            70,
                            70,
                            {'class': 'img-fluid', 'alt': 'Miniature de la galerie "' ~ galery.title ~ '"'},
                            {'fit': 'crop'}
                        ) }}
                    </a>
                </figure>
                <div class="post-content">
                    <h6 class="post-title">
                        <a href="{{ path('galery.show', {slug: galery.slug}) }}">{{ galery.title }}</a> 
                    </h6>
                    <div class="meta">
                        <span class="date">{{ galery.getCreatedAt()|localizeddate('medium', 'none') }}</span>
                        <span class="custom-comments fill-dark size-16">
                            {{ include('icon/comments.html.twig') }}
                            {{ galery.comments|length }}
                        </span>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
    <!-- /.image-list --> 
</div>
<!-- /.widget --> 

templates/galery/_preview.html.twig
{% import 'component/macros.html.twig' as macros %}

<div class="swiper-container-wrapper swiper-preview image-grid swiper-col{{ col }}" data-aos="fade">
    <div class="swiper-container text-center">
        <div class="swiper-wrapper">
            {% for galery in galeries %}
            <div class="swiper-slide">
                <a href="{{ path('galery.show', {slug: galery.slug}) }}">
                    <figure class="overlay overlay4">
                        {{ macros.image(
                            vich_uploader_asset(galery, 'thumbnailFile'),
                            360,
                            360,
                            {'class': 'img-fluid', 'alt': 'Miniature de la galerie "' ~ galery.title ~ '"'},
                            {'fit': 'crop'}
                        ) }}
                    </figure>
                    <div class="post-content text-left gallery-slider pt-5">
                        <div class="meta">
                            <span class="title lead2">{{ galery.title }}</span><br>
                            <span class="date">{{ galery.getCreatedAt()|localizeddate('medium', 'none') }}</span>
                            <span class="pictures fill-dark size-16">
                                {{ include('icon/pictures.html.twig') }}
                                {{ galery.attachments|length }}
                            </span>
                            <span class="custom-comments fill-dark size-16">
                                {{ include('icon/comments.html.twig') }}
                                {{ galery.comments|length }}
                            </span>
                            {% if col is same as('3') %}
                                <span class="likes fill-dark size-16">
                                    {{ include('icon/heart.html.twig') }}
                                    {{ galery.userLikes|length }}
                                </span>
                            {% endif %}
                        </div>
                    </div>
                </a>
            </div>
            <!--/.swiper-slide -->
            {% endfor %}
        </div>
        <!-- /.swiper-wrapper -->
    </div>
{% if col is same as('3') %}
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
{% endif %}
    <!-- .swiper-container -->
    <div class="swiper-pagination gap-large"></div>
</div>
<!-- .swiper-container-wrapper -->

templates/galery/index.html.twig
{% import 'component/macros.html.twig' as macros %}
{% extends 'base.html.twig' %}

{% set title = 'Les galeries' %}

{% block body %}
<div class="wrapper image-wrapper bg-image inverse-text" data-image-src="{{ asset('assets/galery_header.png') }}" style="background-image: url({{ asset('assets/galery_header.png') }});">
  <div class="container inner pt-120 pb-120 text-center">
    <h1 class="sub-heading2 text-center text-uppercase letterspace-8">Annuaire des galeries</h1>
  </div>
  <!-- /.container -->
</div>
<!-- /.wrapper -->
<div class="wrapper light-wrapper">
  <div class="container">
    <div class="space50"></div>
    <div id="cube-grid-filter" class="cbp-filter-container text-center">
      <div data-filter="*" class="cbp-filter-item-active cbp-filter-item">Tout</div>
      {% for category in categories %}
      <div data-filter=".{{ category.translitname }}" class="cbp-filter-item">{{ category.name }}</div>
      {% endfor %}
    </div>
    <div class="section-title-underline"></div>
    <div class="space70"></div>
    <div id="cube-grid" class="cbp text-center">
      {% for galery in galeries %}
      <div class="cbp-item {{ galery.categoriesName }}">
        <figure class="overlay overlay2 overlay-info hovered">
          <a href="{{ path('galery.show', {slug: galery.slug}) }}">
            {{ macros.image(
                vich_uploader_asset(galery, 'thumbnailFile'),
                370,
                370,
                {'class': 'img-fluid', 'alt': 'Miniature de la galerie "' ~ galery.title ~ '"'},
                {'fit': 'crop'}
            ) }}
          </a>
          <figcaption class="d-flex">
            <div class="gallery-list align-self-end mt-auto">
              <h4 class="post-title">{{ galery.title }}</h2>
                <div class="meta">
                  <span class="date">
                    {{ galery.getCreatedAt()|localizeddate('medium', 'none') }}
                  </span>
                  <span class="pictures fill-light size-16">
                    {{ include('icon/pictures.html.twig') }}
                    {{ galery.attachments|length }}
                  </span>
                  <span class="custom-comments fill-light size-16">
                    {{ include('icon/comments.html.twig') }}
                    {{ galery.comments|length }}
                  </span>
                  <span class="likes fill-dark size-16">
                    {{ include('icon/heart.html.twig') }}
                    {{ galery.userLikes|length }}
                  </span>
                </div>
            </div>
          </figcaption>
        </figure>
      </div>
      <!--/.cbp-item -->
      {% endfor %}
    </div>
    <!--/.cbp -->
    <div class="space50"></div>
  </div>
  <!-- /.container -->
</div>
<!-- /.wrapper -->
{% endblock %}