src/Entity/Model.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ModelRepository")
 * @Vich\Uploadable
 */
class Model
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $height;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @var File
     * @Vich\UploadableField(mapping="model_thumbnails", fileNameProperty="image")
     */
    private $imageFile;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Galery", inversedBy="models")
     */
    private $galeries;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;

    /**
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $instagram;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthDate;

    public function __construct()
    {
        $this->createdAt = new \DateTime('now');
        $this->updatedAt = new \DateTime('now');
        $this->galeries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function getHeightFormatted(): ?string
    {
        return number_format($this->height / 100, 2, 'm', '');
    }

    public function setHeight(?int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }
    
    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Galery[]
     */
    public function getGaleries(): Collection
    {
        return $this->galeries;
    }

    public function addGalery(Galery $galery): self
    {
        if (!$this->galeries->contains($galery)) {
            $this->galeries[] = $galery;
        }

        return $this;
    }

    public function removeGalery(Galery $galery): self
    {
        if ($this->galeries->contains($galery)) {
            $this->galeries->removeElement($galery);
        }

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function __toString()
    {
        return $this->getName();
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function get($property) {
        if (property_exists($this, $property)) {
            return $this->$property;
        }
        return null;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(?string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(?\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getAge(): ?String
    {
        $now = new DateTime();
        $birth = $this->birthDate;

        return $birth->diff($now)->y;
    }
}

src/Controller/ModelController.php
<?php

namespace App\Controller;

use App\Entity\Model;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ModelRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ModelController extends AbstractController
{
    /**
     * @Route("/modeles", name="models")
     * @param ModelRepository $GaleryRepository
     */
    public function index(ModelRepository $ModelRepository)
    {
        $models = $ModelRepository->findAll();

        return $this->render('model/index.html.twig', [
            'models' => $models,
        ]);
    }

    /**
    * @Route("/model/{slug}", name="model.show")
    * @param Model $model
    * @return Response
    */
    public function show(Model $model, ModelRepository $repository) 
    {
        return $this->render('model/show.html.twig', ['model' => $model]);
    }
}

templates/model/index.html.twig
{% import 'component/macros.html.twig' as macros %}
{% extends 'base.html.twig' %}

{% set title = 'Les modèles' %}

{% block body %}
<div class="wrapper image-wrapper bg-image inverse-text" data-image-src="{{ asset('assets/model_header.png') }}"
    style="background-image: url({{ asset('assets/model_header.png') }});">
    <div class="container inner pb-120 pt-120">
        <h1 class="sub-heading2 text-center text-uppercase letterspace-8">Découvrez les modèles</h1>
    </div>
</div>

<div class="wrapper light-wrapper">
    <div class="container">
        <div class="space50"></div>
        <div class="section-title-underline"></div>
        <div class="space70"></div>
        <div id="cube-grid" class="cbp text-centered">
            {% for model in models %}
            <div class="cbp-item">
                <figure class="overlay overlay5 model">
                    <a href="{{ path('model.show', {slug: model.slug}) }}">
                        {{ macros.image(
                            vich_uploader_asset(model, 'imageFile'),
                            370,
                            370,
                            {'class': 'img-fluid', 'alt': 'Portrait du modèle "' ~ model.name ~ '"'},
                            {'fit': 'crop'}
                        ) }}
                    </a>
                    <figcaption class="d-flex">
                        <div class="align-self-end mx-auto">
                            <h4 class="mb-0">{{ model.name }}</h4>
                        </div>
                    </figcaption>
                </figure>
            </div>
            <!--/.cbp-item -->
            {% endfor %}
        </div>
    </div>
    <!-- .swiper-container-wrapper -->
    <div class="space50"></div>
</div>
<!-- /.wrapper -->
{% endblock %}

templates/model/preview.html.twig
<div class="grid list-view pt-40 text-center">
        <div class="row isotope">
        {% for model in models %}
          <div class="item grid-sizer col-6">
          {# <div class="box box-border"> #}
            <div class="row">
              <div class="col-lg-5">
                <div class="icon icon-img icon-round mb-20">
                    <figure class="model-avatar">
                      {{ macros.image(
                          vich_uploader_asset(model, 'imageFile'),
                          260,
                          260,
                          {'class': 'img-fluid', 'alt': 'Portrait du modèle "' ~ model.name ~ '"'},
                          {'fit': 'crop'}
                      ) }}  
                    </figure>
                </div>
              </div>
              <!--/column -->
              {# <div class="space25 d-none d-md-block d-lg-none"></div> #}
              <div class="col-lg-7">
                <h6 class="mb-5">{{ model.name }}</h6>
                <div class="meta"></div>
                <a href="#" class="more">En voir plus</a>
              </div>
              <!--/column --> 
            </div>
            {# </div> #}
            <!--/.row --> 
          </div>
          <!-- /.post -->
          {% endfor %}
        </div>
        <!-- /.row --> 
      </div>
      <!-- /.grid --> 

templates/model/show.html.twig
{% import 'component/macros.html.twig' as macros %}
{% extends 'base.html.twig' %}

{% set title = 'Modèle - ' ~ model.name %}

{% block body %}
    <div class="wrapper light-wrapper">
        <div class="container">
            <div class="row mb-90 mt-90">
                <div class="col-md-4 offset-1">
                    <figure class="overlay-info">
                        {{ macros.image(
                            vich_uploader_asset(model, 'imageFile'),
                            360,
                            360,
                            {'class': 'img-fluid', 'alt': 'Portrait du modèle "' ~ model.name ~ '"'},
                            {'fit': 'crop'}
                        ) }}  
                    </figure>
                </div>
                <div class="col-md-6 text-md-left text-center">
                    <h1 class="section-title section-title-upper">
                        {{ model.name }}
                        {% if model.instagram %}
                            <a href="{{ model.instagram }}" target="_blank"> <i class="fa fa-instagram"></i></a>
                        {% endif %}
                    </h1>

                    {% if model.birthdate %} <i class="fa fa-birthday-cake"></i> {{ model.age }} ans {% endif %}
                    {% if model.height %} | <i class="si-design_ruler-2"></i> {{ model.heightFormatted }} {% endif %}
                    {% if model.country or model.city %}
                        | <i class="fa fa-map-marker"></i> 
                        {% if model.country and model.city %}
                            {{ model.country }}, {{ model.city }}
                        {% elseif model.country %} 
                            {{ model.country }}
                        {% elseif model.city %} 
                            {{ model.city }}
                        {% endif %}
                    {% endif %}
                    <p>{{ model.description|raw }}</p>
                </div>
            </div>
        {% if model.galeries is not empty %}
            <div class="pl-30 pr-30 mb-80">
                <h2 class="section-title section-title-upper text-left">Ses albums</h2>
                {{ include('galery/_preview.html.twig', { galeries: model.galeries, col: '3' }) }}
            </div>
            <!-- /.container -->
        {% endif %}
        </div>
        <!-- /.container --> 
    </div>
    <!-- /.wrapper -->

{% endblock %}